# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Work/SLSCM-LaB/24092025/test4/MO-EVRP-TW

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Work/SLSCM-LaB/24092025/test4/MO-EVRP-TW

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Work/SLSCM-LaB/24092025/test4/MO-EVRP-TW/CMakeFiles /mnt/d/Work/SLSCM-LaB/24092025/test4/MO-EVRP-TW//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Work/SLSCM-LaB/24092025/test4/MO-EVRP-TW/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mo_evrp_tw

# Build rule for target.
mo_evrp_tw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mo_evrp_tw
.PHONY : mo_evrp_tw

# fast build rule for target.
mo_evrp_tw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/build
.PHONY : mo_evrp_tw/fast

src/ALNS.o: src/ALNS.cpp.o
.PHONY : src/ALNS.o

# target to build an object file
src/ALNS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/ALNS.cpp.o
.PHONY : src/ALNS.cpp.o

src/ALNS.i: src/ALNS.cpp.i
.PHONY : src/ALNS.i

# target to preprocess a source file
src/ALNS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/ALNS.cpp.i
.PHONY : src/ALNS.cpp.i

src/ALNS.s: src/ALNS.cpp.s
.PHONY : src/ALNS.s

# target to generate assembly for a file
src/ALNS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/ALNS.cpp.s
.PHONY : src/ALNS.cpp.s

src/Customer.o: src/Customer.cpp.o
.PHONY : src/Customer.o

# target to build an object file
src/Customer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Customer.cpp.o
.PHONY : src/Customer.cpp.o

src/Customer.i: src/Customer.cpp.i
.PHONY : src/Customer.i

# target to preprocess a source file
src/Customer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Customer.cpp.i
.PHONY : src/Customer.cpp.i

src/Customer.s: src/Customer.cpp.s
.PHONY : src/Customer.s

# target to generate assembly for a file
src/Customer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Customer.cpp.s
.PHONY : src/Customer.cpp.s

src/Depot.o: src/Depot.cpp.o
.PHONY : src/Depot.o

# target to build an object file
src/Depot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Depot.cpp.o
.PHONY : src/Depot.cpp.o

src/Depot.i: src/Depot.cpp.i
.PHONY : src/Depot.i

# target to preprocess a source file
src/Depot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Depot.cpp.i
.PHONY : src/Depot.cpp.i

src/Depot.s: src/Depot.cpp.s
.PHONY : src/Depot.s

# target to generate assembly for a file
src/Depot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Depot.cpp.s
.PHONY : src/Depot.cpp.s

src/Instance.o: src/Instance.cpp.o
.PHONY : src/Instance.o

# target to build an object file
src/Instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Instance.cpp.o
.PHONY : src/Instance.cpp.o

src/Instance.i: src/Instance.cpp.i
.PHONY : src/Instance.i

# target to preprocess a source file
src/Instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Instance.cpp.i
.PHONY : src/Instance.cpp.i

src/Instance.s: src/Instance.cpp.s
.PHONY : src/Instance.s

# target to generate assembly for a file
src/Instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Instance.cpp.s
.PHONY : src/Instance.cpp.s

src/Node.o: src/Node.cpp.o
.PHONY : src/Node.o

# target to build an object file
src/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Node.cpp.o
.PHONY : src/Node.cpp.o

src/Node.i: src/Node.cpp.i
.PHONY : src/Node.i

# target to preprocess a source file
src/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Node.cpp.i
.PHONY : src/Node.cpp.i

src/Node.s: src/Node.cpp.s
.PHONY : src/Node.s

# target to generate assembly for a file
src/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Node.cpp.s
.PHONY : src/Node.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Route.o: src/Route.cpp.o
.PHONY : src/Route.o

# target to build an object file
src/Route.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Route.cpp.o
.PHONY : src/Route.cpp.o

src/Route.i: src/Route.cpp.i
.PHONY : src/Route.i

# target to preprocess a source file
src/Route.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Route.cpp.i
.PHONY : src/Route.cpp.i

src/Route.s: src/Route.cpp.s
.PHONY : src/Route.s

# target to generate assembly for a file
src/Route.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Route.cpp.s
.PHONY : src/Route.cpp.s

src/Station.o: src/Station.cpp.o
.PHONY : src/Station.o

# target to build an object file
src/Station.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Station.cpp.o
.PHONY : src/Station.cpp.o

src/Station.i: src/Station.cpp.i
.PHONY : src/Station.i

# target to preprocess a source file
src/Station.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Station.cpp.i
.PHONY : src/Station.cpp.i

src/Station.s: src/Station.cpp.s
.PHONY : src/Station.s

# target to generate assembly for a file
src/Station.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Station.cpp.s
.PHONY : src/Station.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/Vehicle.o: src/Vehicle.cpp.o
.PHONY : src/Vehicle.o

# target to build an object file
src/Vehicle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Vehicle.cpp.o
.PHONY : src/Vehicle.cpp.o

src/Vehicle.i: src/Vehicle.cpp.i
.PHONY : src/Vehicle.i

# target to preprocess a source file
src/Vehicle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Vehicle.cpp.i
.PHONY : src/Vehicle.cpp.i

src/Vehicle.s: src/Vehicle.cpp.s
.PHONY : src/Vehicle.s

# target to generate assembly for a file
src/Vehicle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/Vehicle.cpp.s
.PHONY : src/Vehicle.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/operators/DestroyOperators.o: src/operators/DestroyOperators.cpp.o
.PHONY : src/operators/DestroyOperators.o

# target to build an object file
src/operators/DestroyOperators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/operators/DestroyOperators.cpp.o
.PHONY : src/operators/DestroyOperators.cpp.o

src/operators/DestroyOperators.i: src/operators/DestroyOperators.cpp.i
.PHONY : src/operators/DestroyOperators.i

# target to preprocess a source file
src/operators/DestroyOperators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/operators/DestroyOperators.cpp.i
.PHONY : src/operators/DestroyOperators.cpp.i

src/operators/DestroyOperators.s: src/operators/DestroyOperators.cpp.s
.PHONY : src/operators/DestroyOperators.s

# target to generate assembly for a file
src/operators/DestroyOperators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/operators/DestroyOperators.cpp.s
.PHONY : src/operators/DestroyOperators.cpp.s

src/operators/RepairOperators.o: src/operators/RepairOperators.cpp.o
.PHONY : src/operators/RepairOperators.o

# target to build an object file
src/operators/RepairOperators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/operators/RepairOperators.cpp.o
.PHONY : src/operators/RepairOperators.cpp.o

src/operators/RepairOperators.i: src/operators/RepairOperators.cpp.i
.PHONY : src/operators/RepairOperators.i

# target to preprocess a source file
src/operators/RepairOperators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/operators/RepairOperators.cpp.i
.PHONY : src/operators/RepairOperators.cpp.i

src/operators/RepairOperators.s: src/operators/RepairOperators.cpp.s
.PHONY : src/operators/RepairOperators.s

# target to generate assembly for a file
src/operators/RepairOperators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mo_evrp_tw.dir/build.make CMakeFiles/mo_evrp_tw.dir/src/operators/RepairOperators.cpp.s
.PHONY : src/operators/RepairOperators.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mo_evrp_tw"
	@echo "... src/ALNS.o"
	@echo "... src/ALNS.i"
	@echo "... src/ALNS.s"
	@echo "... src/Customer.o"
	@echo "... src/Customer.i"
	@echo "... src/Customer.s"
	@echo "... src/Depot.o"
	@echo "... src/Depot.i"
	@echo "... src/Depot.s"
	@echo "... src/Instance.o"
	@echo "... src/Instance.i"
	@echo "... src/Instance.s"
	@echo "... src/Node.o"
	@echo "... src/Node.i"
	@echo "... src/Node.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Route.o"
	@echo "... src/Route.i"
	@echo "... src/Route.s"
	@echo "... src/Station.o"
	@echo "... src/Station.i"
	@echo "... src/Station.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/Vehicle.o"
	@echo "... src/Vehicle.i"
	@echo "... src/Vehicle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/operators/DestroyOperators.o"
	@echo "... src/operators/DestroyOperators.i"
	@echo "... src/operators/DestroyOperators.s"
	@echo "... src/operators/RepairOperators.o"
	@echo "... src/operators/RepairOperators.i"
	@echo "... src/operators/RepairOperators.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

